services:
  server:
    build: ../server
    ports:
      - "8000:8000"
    env_file:
      - ../server/.env

  client:
    build: ../client
    env_file:
      - ../client/.env
    depends_on:
      - server

  viewer:
    build: ../viewer
    ports:
      - "3000:80"
    depends_on:
      - server
